### ISSUE TITLE
Please clarify what has to be in the first column

### ISSUE THREAD

**Issue by silke** [mukil/dmx-csv#5]
I looked at your example file with the bookmarks. I don't understand what the first column has to look like. Could you please clarify or edit the DMX plugin documentation directly? Thanks a lot!

**Comment by mukil** [comment]
Sure, the `.csv` demo files in the `test` directory should help:

See https://github.com/mukil/dmx-csv/tree/master/src/test/resources

**Comment by mukil** [comment]
Sorry, I misunderstood your questions:

So, the first column is responsible for giving topics (instances) an URI. This is/was useful for subsequent imports and if you want to identity `rows` (=topics) by an URI. The values in these columns should be optional.

A topic URI thus is constructed by

- a prefix (the value in cell A:1)
- a suffix (the value in the cell A:N)

I hope this answers your question.

**Comment by mukil** [comment]
So, to clarify, the **first column** in each table **is for** importing **URIs**. 
I am closing this issue now. Please reopen if you have any questions
